package cn.jx.customer.entity;

import cn.jx.common.Entity.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_customer
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CustomerEntity extends BaseEntity {
    /** */
    private Integer uuid;

    /** */
    private String customerid;

    /** */
    private String pwd;

    /** */
    private String showname;

    /** */
    private String truename;

    /** */
    private String registertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.uuid
     *
     * @return the value of tbl_customer.uuid
     *
     * @mbg.generated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.uuid
     *
     * @param uuid the value for tbl_customer.uuid
     *
     * @mbg.generated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.customerId
     *
     * @return the value of tbl_customer.customerId
     *
     * @mbg.generated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.customerId
     *
     * @param customerid the value for tbl_customer.customerId
     *
     * @mbg.generated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.pwd
     *
     * @return the value of tbl_customer.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.pwd
     *
     * @param pwd the value for tbl_customer.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.showName
     *
     * @return the value of tbl_customer.showName
     *
     * @mbg.generated
     */
    public String getShowname() {
        return showname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.showName
     *
     * @param showname the value for tbl_customer.showName
     *
     * @mbg.generated
     */
    public void setShowname(String showname) {
        this.showname = showname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.trueName
     *
     * @return the value of tbl_customer.trueName
     *
     * @mbg.generated
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.trueName
     *
     * @param truename the value for tbl_customer.trueName
     *
     * @mbg.generated
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.registerTime
     *
     * @return the value of tbl_customer.registerTime
     *
     * @mbg.generated
     */
    public String getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.registerTime
     *
     * @param registertime the value for tbl_customer.registerTime
     *
     * @mbg.generated
     */
    public void setRegistertime(String registertime) {
        this.registertime = registertime;
    }

    @Override
    public String toString() {
        return "CustomerEntity{" +
                "uuid=" + uuid +
                ", customerid='" + customerid + '\'' +
                ", pwd='" + pwd + '\'' +
                ", showname='" + showname + '\'' +
                ", truename='" + truename + '\'' +
                ", registertime='" + registertime + '\'' +
                '}';
    }
}